name: Rust

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  clippy:
    name: Lint with Clippy - ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    env:
      RUSTFLAGS: -Dwarnings
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        components: clippy
        rust-version: ${{ matrix.rust }}
    - uses: Swatinem/rust-cache@v1
    - name: Header
      run: rustc -Vv
    - name: clippy
      run: cargo clippy --verbose --bins

  test-versions:
    name: Test Rust - nightly
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: Swatinem/rust-cache@v1
    - name: Header
      run: rustc -Vv
    - name: test
      run: cargo test --verbose

  code-coverage:
    name: Generate code coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v1
    - uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.27.2'
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
